### PR TITLE
Add BitBucket Auth

### PR DESCRIPTION
**Pull request by cyberox**
Added support for BitBucket Cloud Authentication

### CODE REVIEW

**Comment by cyberox** [comment]
Can close issue #13

**Comment by crsimmons** [comment]
Hi @cyberox, thanks for the PR! It looks good apart from one thing.

The new functionality isn't being tested as part of the `system-test-zone-delegation` system test (nor should it be) but you've added the `BITBUCKET_AUTH_CLIENT_ID` and `BITBUCKET_AUTH_CLIENT_SECRET` env vars to `ci/tasks/system-test-zone-delegation.yml ` and the two jobs for that test in `ci/pipeline.yml `. If you could remove these refereces then I'll merge.

**Comment by crsimmons** [comment]
LGTM. Once it passes tests in our CI I'll cut a release.

**Comment by crsimmons** [comment]
Released in https://github.com/EngineerBetter/control-tower/releases/tag/0.14.0

**Pull request merged**
